id: I3B3952AA
ocr_import_info:
  timestamp: '2023-06-24T04:45:43.703927+00:00'
  batch_id: batch-58ca
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-24 04:58:51.851307+00:00
last_modified: 2023-06-24 04:58:51.851312+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3554
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3554
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བ་ཤེས་རབ།
  languages:
  - bo
  author: སློབ་དཔོན་ཀླུ་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9966738963351449
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG3624:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3624
      total_pages: 106
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3624.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9966738963351449
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
